---
title: "Phyllochron data analysis report"
author: "Dana Looschelders"
date: "30 4 2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(agricolae)
library(PMCMRplus)
library(PMCMR)
library(tidyverse)
library(MASS)
library(rmarkdown)

setwd("C:/00_Dana/Uni/Internship/Work/Data Rosemount/")
#read in phyllochron data as list
files_list=list.files(pattern ="^Leaf Phyllochron")
list_phyllo=list()
list_phyllo=lapply(files_list, read.csv2)
#remove empty columns from dataframes in list_phyllo 
#would be neater with to do it with lapply 
for (i in 1:length(list_phyllo)){
  list_phyllo[[i]]=Filter(function(x)!all(is.na(x)), list_phyllo[[i]])
}
files_list_short=substr(files_list, start = 1, stop=20) #create mames for list
names(list_phyllo)=files_list_short

```

```{r}
  name_phyllo=names(list_phyllo[1])
  data=list_phyllo[[i]]
  for (x in 5:6) {
    name_month=names(data[x])
    print(paste(name_phyllo, "for", name_month))
    print("DATA EXPLORATION")
    #histogram for phyllochron values
    print(summary(data[,x]))
    hist(data[,x], main=paste(name_phyllo, "for", name_month))
    #boxplot for treatment
    boxplot(data[,x]~data$Treatment, main=paste(name_phyllo, "for", name_month))
    #boxplot for Variety with display of names as labels
    labels=unique(data$Variety)
    boxplot(data[,x]~data$Variety, 
            main=paste(name_phyllo, "for", name_month),
            ylab="Days",
            xaxt = "n",  xlab = "")
    axis(1, labels = FALSE)
    # Plot x labs at default x position
    text(x=labels,y = par("usr")[1] - 0.1, srt = 60, adj = 0.5,
         labels = labels, xpd = TRUE)
    print("NORMALITY TEST")
    qqnorm(data[,x])
    qqline(data[,x])
    print(shapiro.test(data[,x]))
    test.shapiro=shapiro.test(data[,x])
    if(test.shapiro[[2]]<0.05){
      print("Based on shapiro test normality cannot be assumed")
    print(wilcox.test(data[,x]~data$Treatment))
    print(kruskal.test(data[,x]~data$Variety))
    test.kruskal=kruskal.test(data[,x]~data$Variety)
    if(test.kruskal[[3]]<0.05){
      print("As the Kruskal test is significant a posthoc test will be performed")
    print(posthoc.kruskal.nemenyi.test(data[,x]~data$Variety))
    } else {print("The Varieties don't differ significantly")}
    } else {print("Normal distribution can be assumed")}
  }
```
```{r}
head(list_phyllo[[1]][6:7])
```
The Phyllochron for July, August and September could't be analysed as it was the same for all plants and therefore there was no significant difference

## Data Exploration, Normality Test and Significance tests


```{r}
for (i in 2:length(list_phyllo)) {
  name_phyllo=names(list_phyllo[i])
  data=list_phyllo[[i]]
  for (x in 5:8) {
    name_month=names(data[x])
    name_month=names(data[x])
    print(paste(name_phyllo, "for", name_month))
    print("DATA EXPLORATION")
    #histogram for phyllochron values
    print(summary(data[,x]))
    hist(data[,x], main=paste(name_phyllo, "for", name_month))
    #boxplot for treatment
    boxplot(data[,x]~data$Treatment, main=paste(name_phyllo, "for", name_month))
    #boxplot for Variety with display of names as labels
    labels=unique(data$Variety)
    boxplot(data[,x]~data$Variety, 
            main=paste(name_phyllo, "for", name_month),
            ylab="Days",
            xaxt = "n",  xlab = "")
    axis(1, labels = FALSE)
    # Plot x labs at default x position
    text(x=labels,y = par("usr")[1] - 0.1, srt = 60, adj = 0.5,
         labels = labels, xpd = TRUE)
    print("NORMALITY TEST")
    qqnorm(data[,x])
    qqline(data[,x])
    print(shapiro.test(data[,x]))
    test.shapiro=shapiro.test(data[,x])
    if(test.shapiro[[2]]<0.05){
      print("Based on shapiro test normality cannot be assumed")
    print(wilcox.test(data[,x]~data$Treatment))
    print(kruskal.test(data[,x]~data$Variety))
    test.kruskal=kruskal.test(data[,x]~data$Variety)
    if(test.kruskal[[3]]<0.05){
      print("As the Kruskal test is significant a posthoc test will be performed")
    print(posthoc.kruskal.nemenyi.test(data[,x]~data$Variety))
    } else {print("The Varieties don't differ significantly")}
    } else {print("Normal distribution can be assumed")}
  }
}
```


